const cities = [
  {
    Pierce: [
      "Bonney Lake",
      "Buckley",
      "DuPont",
      "Edgewood",
      "Fife",
      "Fircrest",
      "Gig Harbor",
      "Lakewood",
      "Milton",
      "Orting",
      "Pacific",
      "Puyallup",
      "Roy",
      "Ruston",
      "Sumner",
      "Tacoma",
      "University Place",
    ],
  },
  {
    King: [
      "Algona",
      "Auburn",
      "Bellevue",
      "Black Diamond",
      "Bothell ",
      "Burien",
      "Carnation",
      "Clyde Hill",
      "Covington",
      "Des Moines",
      "Duvall",
      "Enumclaw",
      "Federal Way",
      "Issaquah",
      "Kenmore",
      "Kent",
      "Kirkland",
      "Lake Forest Park",
      "Maple Valley",
      "Medina",
      "Mercer Island",
      "Milton",
      "Newcastle",
      "Normandy Park",
      "North Bend",
      "Pacific",
      "Redmond",
      "Renton",
      "Sammamish",
      "SeaTac",
      "Seattle",
      "Shoreline",
      "Snoqualmie",
      "Tukwila",
      "Woodinville",
    ],
  },
  {
    Thurston: ["Lacey", "Olympia", "Tenino", "Tumwater", "Ranier", "Yelm"],
  },
];

export { cities };
